# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/fintrack
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate cria/atualiza tabelas automaticamente ao iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Chave secreta para assinar os JWT (mínimo 256 bits)
jwt.secret=fintrack-super-secret-key-must-be-at-least-256-bits-long!!
# Access token expira em 15 minutos (em milissegundos)
jwt.expiration=900000

server.port=8080
